var pointsData = {
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { "Docket Number": "14-9496", "WordsString": "constitutional: 13 unreasonable: 10 determination: 9 ", "Case Name_y": "Manuel v. Joliet", "Date Argued_x": "10\/05\/16", "Area*": "Civil Rights", "Decision": "6-2", "Status": "affirmed", "Court Leaning": "Major Majority", "Previous Court": "7th Circuit", "City": "Joilet, Illinois", "Latitude": 41.525031, "Longitude": -88.081725, "Summary": "Challenging pretrial detention in a criminal case based on the 4th Amendment (unreasonable search & seizure)" }, "geometry": { "type": "Point", "coordinates": [ -88.081725, 41.525031 ] } },
{ "type": "Feature", "properties": { "Docket Number": "15-1262", "WordsString": "congressional: 16 retrogression: 7 predominance: 7 ", "Case Name_y": "McCrory v. Harris", "Date Argued_x": "12\/05\/16", "Area*": "Civil Rights", "Decision": "5-3", "Status": "Affirmed", "Court Leaning": "Liberal", "Previous Court": "District Court of the Middle District of North Carolina", "City": "Raleigh, North Carolina", "Latitude": 35.77959, "Longitude": -78.638179, "Summary": "Challenging 'impermissible racial gerrymandering' based on the 14th Amendment (Equal Protection Clause for voting)" }, "geometry": { "type": "Point", "coordinates": [ -78.638179, 35.77959 ] } },
{ "type": "Feature", "properties": { "Docket Number": "15-1500", "WordsString": "indemnification: 18 jurisdiction: 5 nondiscretionary: 5 ", "Case Name_y": "Lewis v. Clarke", "Date Argued_x": "01\/09\/17", "Area*": "Civil Rights", "Decision": "8-0", "Status": "Reversed and remanded", "Court Leaning": "Major Majority", "Previous Court": "Connecticut Supreme Court", "City": "Norwalk, Connecticut", "Latitude": 41.06391, "Longitude": -73.23594, "Summary": "Challenging whether tribal soverign immunity applies to individuals during civil court case" }, "geometry": { "type": "Point", "coordinates": [ -73.23594, 41.06391 ] } },
{ "type": "Feature", "properties": { "Docket Number": "15-497", "WordsString": "compensatory: 9 rehabilitation: 7 circumstance: 6 ", "Case Name_y": "Fry v. Napoleon Community Schools", "Date Argued_x": "10\/31\/16", "Area*": "Civil Rights", "Decision": "8-0", "Status": "affirmed", "Court Leaning": "Major Majority", "Previous Court": "6th Circuit ", "City": "Detriot, Michigan ", "Latitude": 42.331427, "Longitude": -83.045754, "Summary": "Challenging whether ADA and IDEA always permits trained service dogs in classrooms" }, "geometry": { "type": "Point", "coordinates": [ -83.045754, 42.331427 ] } },
{ "type": "Feature", "properties": { "Docket Number": "15-680", "WordsString": "predominance: 22 redistricting: 12 predominantly: 9 ", "Case Name_y": "Bethune-Hill v. Virginia State Bd. of Elections", "Date Argued_x": "12\/05\/16", "Area*": "Civil Rights", "Decision": "8-0", "Status": "affirmed", "Court Leaning": "Major Majority", "Previous Court": "District Court of Virginia", "City": "Richmond, Virginia", "Latitude": 37.540725, "Longitude": -77.436048, "Summary": "Challenging redistricting in Virginia based on the 14th Amendment's Equal Protection Clause" }, "geometry": { "type": "Point", "coordinates": [ -77.436048, 37.540725 ] } },
{ "type": "Feature", "properties": { "Docket Number": "15-827", "WordsString": "circumstances: 7 appropriately: 6 disabilities: 5 ", "Case Name_y": "Endrew F. v. Douglas County School Dist.", "Date Argued_x": "01\/11\/17", "Area*": "Civil Rights", "Decision": "8-0", "Status": "Vacated and Remanded", "Court Leaning": "Major Majority", "Previous Court": "10th Circuit", "City": "Castle Rock, Colorado", "Latitude": 39.372212, "Longitude": -104.85609, "Summary": "Challenging whether schools district appropriately applied the The Individuals with Disabilities Education Act (IDEA) for individual child" }, "geometry": { "type": "Point", "coordinates": [ -104.85609, 39.372212 ] } },
{ "type": "Feature", "properties": { "Docket Number": "16-309", "WordsString": "naturalization: 71 denaturalization: 11 interpretation: 8 ", "Case Name_y": "Maslenjak v. United States", "Date Argued_x": "04\/26\/17", "Area*": "Civil Rights", "Decision": "9-0", "Status": "Affirmed", "Court Leaning": "Major Majority", "Previous Court": "6th Circuit", "City": "Akron, Ohio", "Latitude": 41.081445, "Longitude": -81.519005, "Summary": "Challenging a naturalization case based on based on an individual who knowingly falsified information (18 U.S.C. 1423)"  }, "geometry": { "type": "Point", "coordinates": [ -81.519005, 41.081445 ] } },
{ "type": "Feature", "properties": { "Docket Number": "16-369", "WordsString": "unreasonable: 26 circumstances: 22 constitutional: 14 ", "Case Name_y": "County of Los Angeles v. Mendez", "Date Argued_x": "03\/22\/17", "Area*": "Civil Rights", "Decision": "8-0", "Status": "Affirmed ", "Court Leaning": "Major Majority", "Previous Court": "9th Circuit", "City": "Los Angeles, California", "Latitude": 34.052234, "Longitude": -118.243685, "Summary": "Challenging use of force during a 4th Amendment case" }, "geometry": { "type": "Point", "coordinates": [ -118.243685, 34.052234 ] } },
{ "type": "Feature", "properties": { "Docket Number": "16-399", "WordsString": "discrimination: 74 jurisdiction: 28 jurisdictional: 27 ", "Case Name_y": "Perry v. Merit Systems Protection Bd.", "Date Argued_x": "04\/17\/17", "Area*": "Civil Rights", "Decision": "7-2", "Status": "Reversed", "Court Leaning": "Liberal", "Previous Court": "District of Columbia Court of Appeals", "City": "Washington, D.C.", "Latitude": 38.907192, "Longitude": -77.036871, "Summary": "Challenging where federal employees can appeal decisions made by the Merit Systems Protection Board" }, "geometry": { "type": "Point", "coordinates": [ -77.036871, 38.907192 ] } }
]
}